apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "zulip.fullname" . }}
  labels:
    app: {{ template "zulip.name" . }}
    chart: {{ template "zulip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zulip.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zulip.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DISABLE_HTTPS
              value: "True"
            - name: SETTING_EXTERNAL_HOST
              value: "{{ .Values.externalHost }}"
            - name: DB_HOST
              value: {{ template "zulip.postgresql.fullname" . }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "zulip.postgresql.fullname" . }}
                  key: postgres-password
            - name: SECRETS_postgres_password
              valueFrom:
                secretKeyRef:
                  name: {{ template "zulip.postgresql.fullname" . }}
                  key: postgres-password
            - name: SETTING_MEMCACHED_LOCATION
              value: {{ template "zulip.memcached.fullname" . }}
            - name: SETTING_RABBITMQ_HOST
              value: {{ template "zulip.rabbitmq.fullname" . }}
            - name: SECRETS_rabbitmq_password
              valueFrom:
                secretKeyRef:
                  name: {{ template "zulip.rabbitmq.fullname" . }}
                  key: rabbitmq-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
