{{- $fullName := include "zulip.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "zulip.name" . }}
    chart: {{ template "zulip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
    backend:
      serviceName: {{ $fullName }}
      servicePort: http
    tls:
      - secretName: {{ template "zulip.fullname" . }}-tls-cert
        hosts:
          - {{ .Values.externalHost }}
